package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Check visibility of elements in page header")
    void generatedTest() {
        step("Open https://www.t1-consulting.ru", () -> {
            step("// todo: just add selenium action");
        });

        step("The elements should be visible:", () -> {
            step("// todo: just add selenium action");
        });

        step("\"О компании\", \"Услуги\", \"Карта решений\", \"Продукты\", \"Контакты\"", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.t1-consulting.ru'", () ->
            open("https://www.t1-consulting.ru"));

        step("Page title should have text '«Т1 Консалтинг»'", () -> {
            String expectedTitle = "«Т1 Консалтинг»";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.t1-consulting.ru'", () ->
            open("https://www.t1-consulting.ru"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}